# Generated by Django 4.2.2 on 2023-07-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_price_categories_customer_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('house_no', models.IntegerField()),
                ('ph', models.IntegerField()),
                ('type', models.CharField(choices=[('Organic', 'Organic'), ('Plastic', 'Plastic'), ('Glass', 'Glass'), ('Electronic', 'Electronic')], default='Plastic', max_length=100)),
                ('number_of_bags', models.IntegerField()),
            ],
        ),
    ]
