# Generated by Django 4.2.2 on 2023-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_booking_cardname_booking_cardnumber_booking_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
