# Generated by Django 4.2.2 on 2023-07-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_booking_cname_alter_booking_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cardname',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='house_no',
        ),
    ]
