# Generated by Django 4.2.2 on 2023-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_booking_cardname_remove_booking_cardnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_bags',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ph',
            field=models.IntegerField(null=True),
        ),
    ]
